%yaml
name: poc-p1-env
    channels:
      - defaults
    dependencies:
      - pip:
        - faiss-cpu==1.8.0
        - sentence-transformers==3.0.1
        - gradio==4.41.0
        - python-dotenv==1.0.1
        - together==1.2.0
        - ollama==0.3.1
        - uvicorn==0.30.3
        - fastapi==0.111.1
        - databricks-langchain
        - databricks-vectorsearch
        - databricks-ai-bridge
        - databricks-sdk==0.65.0
        - databricks-openai
        - pyspark>=3.5.0
        - delta-spark>=3.0.0
        - PyYAML>=6.0
        - databricks-agents
        - mlflow[databricks]
        - langchain
        - langchain_core
        - bs4
        - markdownify
        - pydantic
        - pandas
        - openpyxl
        - langdetect
        - pyaml